# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none
# - master

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'ccdac091-b280-4063-a795-bc4968da3488'
  
  # Web app name
  webAppName: 'nowlab-erebus-app'

  # Environment name
  environmentName: 'nowlab'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build Stage
  jobs:
  - job: BuildJob
    displayName: Build Job
    pool:
      vmImage: $(vmImageName)
    
    steps:
      - script: |
          echo "Date Timestamp is: $(date +%Y%m%d%H%M%S)"
        displayName: 'Run Script'