/* Parameters */        
// def key1 = "${VALUE1}"
// def key2 = "${VALUE2}"
// def key3 = "${VALUE3}"

/* Pipeline */
pipeline {
  agent any
  options {
    timeout(time: 20, unit: 'MINUTES')
  }
  stages {
    stage("Build Image") {
      steps {
        echo "Build Image..."
        sh 'oc process -f templates/build-erebus.yml | oc apply -f -'
        sh 'oc start-build erebus --wait'
      }
    }  
    stage("Deploy Pod") {
      steps {
        echo "Deploy Pod"
        sh 'oc process -f templates/deploy-erebus.yml | oc apply -f -'
      }
    }
  }
}