apiVersion: apps/v1
kind: Deployment
metadata:
  name: erebus
  monitor: true
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erebus
  template:
    metadata:
      labels:
        app: erebus
    spec:
      containers:
      - name: erebus
        image: pangealab/erebus:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: erebus
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: erebus          
