# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none
# - master

variables:

  # Variables
  key1: 'value1'
  key2: 'value2'
  key3: 'value3'

pool:
  vmImage: 'ubuntu-latest'

stages:

  - stage: Build
    jobs:
      - job: Build
        steps:
        - task: Maven@3
          displayName: 'Maven Package'
          inputs:
            mavenPomFile: 'pom.xml'
            mavenOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.8'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            goals: 'package'
            options: '-DskipTests=true'

        - task: CopyFiles@2
          displayName: 'Stage Files'
          inputs:
            SourceFolder: 'target'
            Contents: '*.war'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

        # - publish: '$(Build.ArtifactStagingDirectory)'
        #   displayName: 'Publish Files'
        #   artifact: erebus

        - task: UniversalPackages@0
          inputs:
            command: 'publish'
            publishDirectory: '$(Build.ArtifactStagingDirectory)'
            feedsToUsePublish: 'internal'
            # vstsFeedPublish: '6c4ecf6c-745f-4968-b374-452b2731c1c5/54305083-d19e-4d78-b746-0631a07c2d16'
            vstsFeedPublish: 'nowlab/erebus'
            vstsFeedPackagePublish: 'erebus'
            versionOption: 'patch'
            packagePublishDescription: 'Latest'