# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none
# - master

variables:

  # Variables
  key1: 'value1'
  key2: 'value2'
  key3: 'value3'

pool:
  vmImage: 'ubuntu-latest'

stages:

  - stage: Build
    jobs:
      - job: Build
        steps:
        - task: Maven@3
          displayName: 'Maven Package'
          inputs:
            mavenPomFile: 'pom.xml'
            mavenOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.8'
            jdkArchitectureOption: 'x64'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            goals: 'package'
            options: '-DskipTests=true'

        - task: CopyFiles@2
          displayName: 'Stage Files'
          inputs:
            SourceFolder: 'target'
            Contents: '*.war'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: UniversalPackages@0
          inputs:
            command: 'publish'
            publishDirectory: '$(Build.ArtifactStagingDirectory)'
            feedsToUsePublish: 'internal'
            vstsFeedPublish: 'de661523-a2b5-4fb4-ba2c-4286be7c3565/825f2797-5bcb-44d5-b663-7f17f3dd96b7'
            vstsFeedPackagePublish: 'erebus'
            versionOption: 'major'
            verbosity: 'Information'