# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  vmImageName: 'ubuntu-latest'

pool:
  vmImage: $(vmImageName)

stages:
  - stage: Stage1
    jobs:
      - job: Stage1Job1
        steps:
        - script: echo Hello, world!
          displayName: 'Run a one-line script'

      - job: Stage1Job2
        steps:
        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'

  - stage: Stage2
    dependsOn: Stage1 
    condition: succeed()
    jobs:
      - job: Stage2Job1
        steps:
        - script: echo Hello, world!
          displayName: 'Run a one-line script'

      - job: Stage2Job2
        steps:
        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          displayName: 'Run a multi-line script'