# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  vmImageName: 'ubuntu-latest'

pool:
  vmImage: $(vmImageName)

stages:
  - stage: Stage1
    jobs:
      - job: Job1
        steps:
        - script: echo Hello, world!
          name: Step1
          displayName: 'Run a one-line script'
        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          name: Step2
          displayName: 'Run a multi-line script'

  - stage: Stage2
    jobs:
      - job: Job2
        steps:
        - script: echo Hello, world!
          name: Step3
          displayName: 'Run a one-line script'
        - script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
          name: Step4
          displayName: 'Run a multi-line script'