# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none
# - master

variables:
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: 'ce93bbfe-a41f-4f50-b073-5080d872326b'  

stages:
- stage: Deploy 
  displayName: Deploy Stage
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: AzureCLI@1
      inputs:
        azureSubscription: $(azureSubscription)
        scriptLocation: 'inlineScript'
        inlineScript: 'az group create -n "nowlab-erebus-rg" -l "eastus"'