# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none
# - master

variables:

  ### Variables ###
  azureSubscription: 'Pay-As-You-Go Sandbox(fe82a5ab-cf22-4f8e-be43-2d2aaaebdda7)'
  webAppName: 'nowlab-erebus-app'
  environmentName: 'nowlab'
  vmImageName: 'ubuntu-latest'
  resourceGroup: 'nowlab-erebus-rg'
  servicePlan: 'nowlab-erebus-sp'
  region: 'eastus'
  sku: 'B1'

pool:
  vmImage: 'ubuntu-latest'

stages:

  ### Install Tools Stage ###
  - stage: Tools
    jobs:
      - job: Tools
        steps:
        - bash: |
            set -x # Echo Commands
            # Instal NOWCLI
            pip3 install setuptools
            pip3 install nowcli==1.0.4
          displayName: 'Install NOWCLI'
 
  ### Initialize Azure Stage ###
  - stage: Init
    jobs:
      - job: Init
        steps:

        ### Create Resource Group  ###
        - task: AzureCLI@2
          displayName: 'Create Resource Group'
          inputs:
            azureSubscription: $(azureSubscription)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              set -x # Echo Commands
              az group create -n $(resourceGroup) -l $(region)

        ### Create Service Plan  ###
        - task: AzureCLI@2
          displayName: 'Create Service Plan'
          inputs:
            azureSubscription: $(azureSubscription)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              set -x # Echo Commands
              az appservice plan create -n $(servicePlan) -g $(resourceGroup) -l $(region) --sku $(sku) --is-linux

  ### Deploly App Stage ###
  - stage: Deploy
    jobs:
      - job: Deploy
        steps:

        ### Pre-Create App ###
        - task: AzureCLI@2
          displayName: 'Create App'
          inputs:
            azureSubscription: $(azureSubscription)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              set -x # Echo Commands
              az webapp create -n $(webAppName) -p $(servicePlan) -g $(resourceGroup) --runtime 'TOMCAT|8.5-jre8'

        ### Download WAR ###
        - task: DownloadPipelineArtifact@2
          displayName: 'Download App'
          inputs:
            artifact: drop
        
        ### Deploy WAR to App ###
        - task: AzureWebApp@1
          displayName: 'Deploy App'
          inputs:
            azureSubscription: $(azureSubscription)
            appType: 'webAppLinux'
            appName: 'nowlab-erebus-app'
            package: '$(Pipeline.Workspace)/drop/**/target/*.?(war|jar)'
            appSettings: 'JAVA_OPTS=-Dserver.port=80'