# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    AWS_IP=$(curl http://checkip.amazonaws.com)
    AWS_MESSAGE="ADO `date +%Y%m%d%H%M%S`"
  displayName: 'Get ADO IP Address'

- task: AWSCLI@1
  inputs:
    awsCredentials: 'advlab'
    regionName: 'us-east-2'
    awsCommand: 'ec2'
    awsSubCommand: 'authorize-security-group-ingress'
    awsArguments: '--group-id sg-0086368b819578e1c --ip-permissions "IpProtocol=-1,IpRanges=[{CidrIp=$AWS_IP/32,Description=$AWS_MESSAGE}]"'